import tailwindcssAnimate from "tailwindcss-animate"

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './index.html',
  ],
  // Safelist critical classes that should never be purged
  safelist: [
    // Animation classes
    'animate-spring-in',
    'animate-spring-out',
    'animate-bounce-in',
    'animate-slide-up',
    'animate-slide-down',
    'animate-fade-in',
    'animate-shimmer',
    'animate-wave',
    'animate-pulse-subtle',
    'animate-celebration',
    'animate-ripple',
    'animate-modal-spring-in',
    'animate-modal-spring-out',
    'animate-bottom-sheet-spring-in',
    'animate-bottom-sheet-spring-out',
    'animate-spinner',
    'animate-checkmark',
    'animate-draw-line',
    'animate-progress-fill',
    'animate-counter-pop',
    // Performance optimization classes
    'contain-layout',
    'contain-paint',
    'contain-size',
    'contain-strict',
    'will-change-transform',
    'will-change-opacity',
    'will-change-auto',
    // Glassmorphism classes
    'glass-surface',
    'glass-surface-dark',
    'glass-overlay',
    'glass-card',
    'modal-glass',
    'modal-glass-dark',
    // Micro-interaction classes
    'hover-lift',
    'hover-glow',
    'press-effect',
    'focus-ring-spring',
    'smooth-color',
    'card-hover',
    'btn-hover-scale',
    'input-focus-animate',
    'nav-item-transition',
    // Theme classes
    'theme-transitioning',
    'theme-toggle-button',
    'theme-toggle-icon',
    'theme-preview-card',
    'high-contrast',
    // Page transition classes
    'page-enter-fade',
    'page-exit-fade',
    'page-enter-slide',
    'page-exit-slide',
    'page-enter-scale',
    'page-exit-scale',
    'page-enter-spring',
    'page-exit-spring',
    // Accessibility classes
    'skip-to-main',
    'sr-only',
    // Utility classes
    'architex-gradient',
    'architex-text-gradient',
    'sidebar-no-scrollbar',
    'stagger-children',
    // Mobile optimization classes
    'touch-scroll',
    'touch-scroll-x',
    'touch-scroll-both',
    'momentum-scroll',
    'smooth-touch-scroll',
    'snap-scroll-x',
    'snap-scroll-item',
    'touch-target',
    'touch-target-lg',
    'touch-spacing',
    'touch-spacing-lg',
    'no-touch-select',
    'touch-feedback',
    'pull-to-refresh-container',
    'mobile-list',
    'mobile-card',
    'swipeable',
    'swipe-container',
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        architex: {
          primary: "hsl(var(--architex-primary))",
          secondary: "hsl(var(--architex-secondary))",
          accent: "hsl(var(--architex-accent))",
          success: "hsl(var(--architex-success))",
          warning: "hsl(var(--architex-warning))",
          error: "hsl(var(--architex-error))",
          info: "hsl(var(--architex-info))",
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.025em' }],
        sm: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.025em' }],
        base: ['1rem', { lineHeight: '1.5rem', letterSpacing: '0' }],
        lg: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.025em' }],
        xl: ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.025em' }],
        '2xl': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.025em' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.025em' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.05em' }],
        '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        '6xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        '7xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        '8xl': ['6rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        '9xl': ['8rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        wave: {
          '0%, 100%': { transform: 'translateX(-100%)' },
          '50%': { transform: 'translateX(100%)' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        wave: 'wave 2s ease-in-out infinite',
        'pulse-subtle': 'pulse-subtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}
